//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testflow.MasterCore.Resources.locale {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class i18n_engineCore_zh {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal i18n_engineCore_zh() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Testflow.MasterCore.Resources.locale.i18n_engineCore_zh", typeof(i18n_engineCore_zh).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 信使处于非激活状态时不能执行消息发送。.
        /// </summary>
        internal static string CannotSendWhenDeactive {
            get {
                return ResourceManager.GetString("CannotSendWhenDeactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 事件入列超时。.
        /// </summary>
        internal static string EventEnqueueTimeOut {
            get {
                return ResourceManager.GetString("EventEnqueueTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 事件队列已溢出。.
        /// </summary>
        internal static string EventQueueOverflow {
            get {
                return ResourceManager.GetString("EventQueueOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误的委托类型：{0}。.
        /// </summary>
        internal static string IncorrectDelegate {
            get {
                return ResourceManager.GetString("IncorrectDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 事件参数类型应为”{0}“。.
        /// </summary>
        internal static string IncorrectParamType {
            get {
                return ResourceManager.GetString("IncorrectParamType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 非法的运行时信息名称：{0}。.
        /// </summary>
        internal static string InvalidRuntimeInfoName {
            get {
                return ResourceManager.GetString("InvalidRuntimeInfoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 非法的运行时对象类型：{0}。.
        /// </summary>
        internal static string InvalidRuntimeObjType {
            get {
                return ResourceManager.GetString("InvalidRuntimeObjType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作超时。.
        /// </summary>
        internal static string OperatoinTimeout {
            get {
                return ResourceManager.GetString("OperatoinTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 测试生成超时。.
        /// </summary>
        internal static string TestGenTimeout {
            get {
                return ResourceManager.GetString("TestGenTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 序列执行超时。.
        /// </summary>
        internal static string TestRunTimeout {
            get {
                return ResourceManager.GetString("TestRunTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 带有入参的SequenceGroup必须和父级的TestProject同时运行。.
        /// </summary>
        internal static string UnexistArgumentSource {
            get {
                return ResourceManager.GetString("UnexistArgumentSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不存在的会话事件：&quot;{0}&quot;。.
        /// </summary>
        internal static string UnexistEvent {
            get {
                return ResourceManager.GetString("UnexistEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不存在ID为”{0}“的运行时会话。.
        /// </summary>
        internal static string UnexistSession {
            get {
                return ResourceManager.GetString("UnexistSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未注册的消息类型：“{0}”。.
        /// </summary>
        internal static string UnregisteredMessage {
            get {
                return ResourceManager.GetString("UnregisteredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前操作系统不支持平台&lt;{0}&gt;。.
        /// </summary>
        internal static string UnsupportedPlatform {
            get {
                return ResourceManager.GetString("UnsupportedPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户终止执行测试序列。.
        /// </summary>
        internal static string UserAbort {
            get {
                return ResourceManager.GetString("UserAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户终止测试序列错误：{0}。.
        /// </summary>
        internal static string UserAbortError {
            get {
                return ResourceManager.GetString("UserAbortError", resourceCulture);
            }
        }
    }
}
