//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testflow.EngineCore.Resources.locale {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class i18n_engineCore_zh {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal i18n_engineCore_zh() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Testflow.EngineCore.Resources.locale.i18n_engineCore_zh", typeof(i18n_engineCore_zh).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误的委托类型：{0}。.
        /// </summary>
        internal static string IncorrectDelegate {
            get {
                return ResourceManager.GetString("IncorrectDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 事件参数类型应为”{0}“。.
        /// </summary>
        internal static string IncorrectParamType {
            get {
                return ResourceManager.GetString("IncorrectParamType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不存在的会话事件：&quot;{0}&quot;。.
        /// </summary>
        internal static string UnexistEvent {
            get {
                return ResourceManager.GetString("UnexistEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不存在ID为”{0}“的运行时会话。.
        /// </summary>
        internal static string UnexistSession {
            get {
                return ResourceManager.GetString("UnexistSession", resourceCulture);
            }
        }
    }
}
