//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testflow.SlaveCore.Resources.locale {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class i18n_SlaveCore_zh {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal i18n_SlaveCore_zh() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Testflow.SlaveCore.Resources.locale.i18n_SlaveCore_zh", typeof(i18n_SlaveCore_zh).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 断言检查变量‘{0}’失败。预期值：‘{1}’；真实值：‘{2}’。.
        /// </summary>
        internal static string AssertFailMessage {
            get {
                return ResourceManager.GetString("AssertFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 信使处于非激活状态时不能执行消息发送。.
        /// </summary>
        internal static string CannotSendWhenDeactive {
            get {
                return ResourceManager.GetString("CannotSendWhenDeactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 事件入列超时。.
        /// </summary>
        internal static string EventEnqueueTimeOut {
            get {
                return ResourceManager.GetString("EventEnqueueTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 事件队列已溢出。.
        /// </summary>
        internal static string EventQueueOverflow {
            get {
                return ResourceManager.GetString("EventQueueOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误的委托类型：{0}。.
        /// </summary>
        internal static string IncorrectDelegate {
            get {
                return ResourceManager.GetString("IncorrectDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 事件参数类型应为”{0}“。.
        /// </summary>
        internal static string IncorrectParamType {
            get {
                return ResourceManager.GetString("IncorrectParamType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 程序集‘{0}’是序列中定义程序集的早期版本。.
        /// </summary>
        internal static string InvalidLibVersion {
            get {
                return ResourceManager.GetString("InvalidLibVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接收到非法的消息“{0}”。.
        /// </summary>
        internal static string InvalidMessageReceived {
            get {
                return ResourceManager.GetString("InvalidMessageReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不支持到类型‘{0}’的转换。.
        /// </summary>
        internal static string InvalidTypeCast {
            get {
                return ResourceManager.GetString("InvalidTypeCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载程序集失败。.
        /// </summary>
        internal static string LoadAssemblyFailed {
            get {
                return ResourceManager.GetString("LoadAssemblyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载方法“{0}”失败。.
        /// </summary>
        internal static string LoadFunctionFailed {
            get {
                return ResourceManager.GetString("LoadFunctionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载类型数据失败。.
        /// </summary>
        internal static string LoadTypeFailed {
            get {
                return ResourceManager.GetString("LoadTypeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作被终止。.
        /// </summary>
        internal static string OperationAborted {
            get {
                return ResourceManager.GetString("OperationAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作超时。.
        /// </summary>
        internal static string OperatoinTimeout {
            get {
                return ResourceManager.GetString("OperatoinTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 运行时异常。.
        /// </summary>
        internal static string RuntimeError {
            get {
                return ResourceManager.GetString("RuntimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to “SetUp”序列执行失败。.
        /// </summary>
        internal static string SetUpFailed {
            get {
                return ResourceManager.GetString("SetUpFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 序列配置为强制失败。.
        /// </summary>
        internal static string StepForceFailed {
            get {
                return ResourceManager.GetString("StepForceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 带有入参的SequenceGroup必须和父级的TestProject同时运行。.
        /// </summary>
        internal static string UnexistArgumentSource {
            get {
                return ResourceManager.GetString("UnexistArgumentSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不存在的会话事件：&quot;{0}&quot;。.
        /// </summary>
        internal static string UnexistEvent {
            get {
                return ResourceManager.GetString("UnexistEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 路径&apos;{1}&apos;下不存在程序集&apos;{0}&apos;。.
        /// </summary>
        internal static string UnexistLibrary {
            get {
                return ResourceManager.GetString("UnexistLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不存在ID为”{0}“的运行时会话。.
        /// </summary>
        internal static string UnexistSession {
            get {
                return ResourceManager.GetString("UnexistSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前序列中不存在名称为“{0}”的变量。.
        /// </summary>
        internal static string UnexistVariable {
            get {
                return ResourceManager.GetString("UnexistVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未注册的消息类型：“{0}”。.
        /// </summary>
        internal static string UnregisteredMessage {
            get {
                return ResourceManager.GetString("UnregisteredMessage", resourceCulture);
            }
        }
    }
}
