//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testflow.SequenceManagerTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JsonStrResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JsonStrResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Testflow.SequenceManagerTest.JsonStrResource", typeof(JsonStrResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Assemblies&quot;:[{&quot;AssemblyName&quot;:&quot;TestAssemblyName&quot;,&quot;Path&quot;:&quot;TestDemoPath&quot;,&quot;Available&quot;:true,&quot;Version&quot;:&quot;1.0.2&quot;},{&quot;AssemblyName&quot;:&quot;mscorlib&quot;,&quot;Path&quot;:&quot;SystemPath&quot;,&quot;Available&quot;:true,&quot;Version&quot;:&quot;1.0.2&quot;}],&quot;TypeDatas&quot;:[{&quot;AssemblyName&quot;:&quot;TestAssemblyName&quot;,&quot;Namespace&quot;:&quot;Testflow.Test&quot;,&quot;Name&quot;:&quot;Algorithm&quot;},{&quot;AssemblyName&quot;:&quot;mscorlib&quot;,&quot;Namespace&quot;:&quot;System&quot;,&quot;Name&quot;:&quot;Int32&quot;},{&quot;AssemblyName&quot;:&quot;TestAssemblyName&quot;,&quot;Namespace&quot;:&quot;System&quot;,&quot;Name&quot;:&quot;Double&quot;}],&quot;Arguments&quot;:[],&quot;Variables&quot;:[],&quot;ExecutionModel&quot;:0,&quot;SetUp&quot;:{&quot;Index&quot;:-1,&quot;Variables&quot;:[],&quot;S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sequenceGroup1Json {
            get {
                return ResourceManager.GetString("sequenceGroup1Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;TypeDatas&quot;:[],&quot;Assemblies&quot;:[],&quot;ExecutionModel&quot;:0,&quot;Variables&quot;:[],&quot;VariableValues&quot;:[],&quot;SetUp&quot;:{&quot;Index&quot;:-1,&quot;Variables&quot;:[],&quot;Steps&quot;:[],&quot;Behavior&quot;:0},&quot;SetUpParameters&quot;:{&quot;Index&quot;:-1,&quot;StepParameters&quot;:null,&quot;VariableValues&quot;:null},&quot;SequenceGroupParameters&quot;:[],&quot;TearDown&quot;:{&quot;Index&quot;:-1,&quot;Variables&quot;:[],&quot;Steps&quot;:[],&quot;Behavior&quot;:0},&quot;TearDownParameters&quot;:{&quot;Index&quot;:-1,&quot;StepParameters&quot;:null,&quot;VariableValues&quot;:null}}.
        /// </summary>
        internal static string testProject1Json {
            get {
                return ResourceManager.GetString("testProject1Json", resourceCulture);
            }
        }
    }
}
